### PR TITLE
Fixed dead zones in 16,1 trackpad.

### PR DESCRIPTION
**Pull request by AdityaGarg8**

### CODE REVIEW

**Comment by aunali1** [comment]
cc @Redecorating

**Comment by aunali1** [comment]
@AdityaGarg8 Please squash the changes into a single commit.

**Comment by AdityaGarg8** [comment]
> @AdityaGarg8 Please squash the changes into a single commit.

Could you please do it. I actually am in middle of some important work.

**Comment by Redecorating** [comment]
It removes the dead zones on my 16,1.

**Pull request merged**
